# Generated by Django 5.2.4 on 2026-09-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="education",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="github_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="languages_spoken",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="session_duration",
            field=models.PositiveIntegerField(
                default=45, help_text="Session duration in minutes"
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="specializations",
            field=models.JSONField(
                blank=True, default=list, help_text="Specific session focus areas"
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="twitter_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
