# Generated by Django 5.2.4 on 2026-08-10 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("course", "Course Completion"),
                            ("assessment", "Skill Assessment"),
                            ("career", "Career Path Completion"),
                        ],
                        default="course",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "verification_code",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "certificates",
                "ordering": ["-issued_at"],
            },
        ),
    ]
