# Generated by Django 5.2.4 on 2026-08-10 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "High School"),
                            ("undergraduate", "Undergraduate"),
                            ("graduate", "Graduate"),
                            ("postgraduate", "Postgraduate"),
                            ("phd", "PhD"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "institution",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                ("career_goals", models.JSONField(blank=True, default=list)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("linkedin_url", models.URLField(blank=True, default="")),
                ("github_url", models.URLField(blank=True, default="")),
                ("portfolio_url", models.URLField(blank=True, default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Profile",
                "db_table": "student_profiles",
            },
        ),
        migrations.CreateModel(
            name="LearningHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("course_enrolled", "Course Enrolled"),
                            ("course_completed", "Course Completed"),
                            ("assessment_completed", "Assessment Completed"),
                            ("career_started", "Career Path Started"),
                            ("milestone_reached", "Milestone Reached"),
                            ("certificate_earned", "Certificate Earned"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_history",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "learning_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("booking_reminders", models.BooleanField(default=True)),
                ("course_updates", models.BooleanField(default=True)),
                ("job_alerts", models.BooleanField(default=True)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("mentors_only", "Mentors Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "student_settings",
            },
        ),
    ]
