# Generated by Django 5.2.4 on 2026-08-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="expected_salary",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="headline",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="job_hunt_status",
            field=models.CharField(
                choices=[
                    ("actively_looking", "Actively Looking"),
                    ("open_to_offers", "Open to Offers"),
                    ("not_looking", "Not Looking"),
                ],
                default="actively_looking",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="notice_period",
            field=models.CharField(blank=True, default="Immediate", max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_locations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="resume_file",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
