# Generated by Django 5.2.4 on 2026-09-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_studentprofile_bio_studentprofile_expected_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="academic_score",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="certifications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="languages_spoken",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="major_or_stream",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="projects_highlights",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="twitter_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
