# Generated by Django 5.2.4 on 2026-09-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentprofile_academic_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="achievements",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="projects",
            field=models.JSONField(
                blank=True, default=list, help_text="List of student project objects"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="job_hunt_status",
            field=models.CharField(
                choices=[
                    ("actively_looking", "Actively Looking"),
                    ("hiring", "Hiring (Recruiter / HR)"),
                    ("working", "Working / Employed"),
                    ("open_to_offers", "Open to Offers"),
                    ("not_looking", "Not Looking"),
                ],
                default="actively_looking",
                max_length=30,
            ),
        ),
    ]
