# Generated by Django 5.2.4 on 2026-08-20 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("courses", "0001_initial"),
        ("students", "0002_studentprofile_bio_studentprofile_expected_salary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("all", "All Platform Students"),
                    ("individual", "Individual Students"),
                    ("course", "Course Enrolled"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="instructions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("graded", "Graded"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="code_submission",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="language",
            field=models.CharField(blank=True, default="python", max_length=50),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="points_awarded",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="selected_options",
            field=models.ManyToManyField(
                blank=True, related_name="attempt_answers", to="assessments.option"
            ),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="test_cases_passed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="test_cases_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="text_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="question",
            name="programming_language",
            field=models.CharField(blank=True, default="python", max_length=50),
        ),
        migrations.AddField(
            model_name="question",
            name="starter_code",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="question",
            name="test_cases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple Choice (Single)"),
                    ("multi_select", "Multiple Choice (Multiple)"),
                    ("true_false", "True / False"),
                    ("text", "Short Text / Essay"),
                    ("coding", "Coding Test"),
                ],
                default="mcq",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AssessmentAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("all", "All Platform Students"),
                            ("individual", "Individual Student"),
                            ("course", "Course Enrolled"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_assignments",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_assessments",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="assessments.assessmentassignment",
            ),
        ),
    ]
