# Generated by Django 5.2.4 on 2026-08-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0002_assessment_assignment_type_assessment_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
