# Generated by Django 5.2.4 on 2026-08-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeprofile",
            name="resume_file",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
