# Generated by Django 5.2.4 on 2026-09-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerpath",
            name="overview_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed career review, why to choose, and skill growth analysis.",
            ),
        ),
        migrations.AddField(
            model_name="careerpath",
            name="skill_growth_highlights",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Key skill benefits and career growth points.",
            ),
        ),
    ]
